# Mergify configuration
# https://docs.mergify.com/configuration/file-format/
#
# Auto-merges PRs from trusted bots when CI passes.
# Requires Mergify GitHub App: https://github.com/apps/mergify

pull_request_rules:
  # Auto-assign all PRs to maintainer
  - name: Auto-assign PRs
    conditions:
      - -draft
    actions:
      assign:
        users:
          - robcohen

  # Auto-merge Dependabot PRs (dependency updates)
  - name: Auto-merge Dependabot PRs
    conditions:
      - author=dependabot[bot]
      - check-success=build
      - -draft
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body | get_section("Release notes") or body }}

  # Auto-merge release-plz PRs (version bumps and changelog)
  - name: Auto-merge release-plz PRs
    conditions:
      - author=github-actions[bot]
      - label=release
      - check-success=build
      - -draft
    actions:
      merge:
        method: merge
        commit_message_template: |
          {{ title }} (#{{ number }})

  # Auto-approve Dependabot PRs (minor/patch updates only)
  - name: Auto-approve Dependabot minor/patch
    conditions:
      - author=dependabot[bot]
      - or:
        - title~=bump .* from .* to .*  # patch/minor
        - title~=update .* requirement
      - -title~=major  # exclude major updates
    actions:
      review:
        type: APPROVE
        message: Auto-approved minor/patch dependency update.

  # Request review for major Dependabot updates
  - name: Request review for major updates
    conditions:
      - author=dependabot[bot]
      - title~=major
    actions:
      comment:
        message: |
          This is a **major** dependency update. Please review carefully for breaking changes.

  # Delete head branch after merge
  - name: Delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
